In [14]:
pip install numpy

You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [15]:
import numpy as np

In [16]:
mylist=[2,3,3]

In [17]:
matrix=[[2,3,4],[5,6,7]]

In [18]:
np.array(matrix)

array([[2, 3, 4],
       [5, 6, 7]])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.random.rand(5,5)

array([[0.68020456, 0.63438   , 0.26658339, 0.82352813, 0.63992571],
       [0.69266129, 0.29642492, 0.24848565, 0.63174266, 0.65499991],
       [0.30386858, 0.80179834, 0.54713319, 0.71248949, 0.01085288],
       [0.09515045, 0.74292191, 0.78444191, 0.65641778, 0.15816565],
       [0.00086272, 0.21109991, 0.16455284, 0.19256096, 0.63449599]])

In [23]:
np

<module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/__init__.py'>